
name: Pre-release

on:
  workflow_run:
    workflows: Build
    branches: master
    types:
      - completed

jobs:
  Upload:  
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Download Packages
      uses: dawidd6/action-download-artifact@master
      with:
        workflow: build.yml
        commit: ${{github.sha}}

    - name: Prepare the Package
      run: mv Infinity-${{github.sha}}/release/app-release-unsigned.apk Infinity-${{github.sha}}.apk

    - name: Upload Pre-release
      uses: marvinpinto/action-automatic-releases@latest
      with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          automatic_release_tag: latest
          title: Development Build
          files: Infinity-${{github.sha}}.apk
